Source code/C-SMS/Areas/Admin/Controllers/NhanVienController.cs
using Business.Implements;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Common.ViewModels;
using System.Threading.Tasks;
using Common.Models;
using System.Net;
using System.IO;
using System.Web.Helpers;
using Common.Ultil;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class NhanVienController : BaseController
    {
        readonly NhanVienBusiness _nhanVienKhoBus = new NhanVienBusiness();
        readonly ChucVuBusiness _chucVuKhoBus = new ChucVuBusiness();
        //
        // GET: /Admin/NhanVien/

        public ActionResult Index()
        {
            List<SelectListItem> trangThai = new List<SelectListItem>();
            trangThai.Add(new SelectListItem { Text = "Đang Hoạt Động", Value = "true" });
            trangThai.Add(new SelectListItem { Text = "Ngừng Hoạt Động", Value = "false" });
            ViewBag.data = trangThai;
            ViewBag.chucvu = _chucVuKhoBus.LoadChucVu();
            return View();
        }

        [HttpGet]
        public JsonResult CheckUserName(string username, string email, string sodienthoai, string cmnd)
        {
            var isDuplicate = false;

            foreach (var user in _nhanVienKhoBus.GetAllUserName())
            {
                if (user.UserName == username)
                    isDuplicate = true;
                if (user.Email == email)
                    isDuplicate = true;
                if (user.SoDienThoai == sodienthoai)
                    isDuplicate = true;
                if (user.CMND == cmnd)
                    isDuplicate = true;
             
            }

            var jsonData = new { isDuplicate };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

       
        public ActionResult DanhSachNhanVien(string searchString, string trangthai, string chucvu , int page = 1, int pageSize = 10)
        {
            if (!string.IsNullOrEmpty(searchString) || !string.IsNullOrEmpty(chucvu))
            {
                return View(_nhanVienKhoBus.SearchDanhSachNhanVien(searchString, trangthai, chucvu).ToPagedList(page, pageSize));
            }
            if (!string.IsNullOrEmpty(trangthai))
            {
                return View(_nhanVienKhoBus.SearchDanhSachNhanVien(searchString, trangthai, chucvu).ToPagedList(page, pageSize));
            }

            return View(_nhanVienKhoBus.LoadDanhSachNhanVien().ToPagedList(page, pageSize));
        }

        public ActionResult ThongTinNhanVien(int id)
        {
            List<SelectListItem> trangThai = new List<SelectListItem>();
            trangThai.Add(new SelectListItem { Text = "Đang Hoạt Động", Value = "true" });
            trangThai.Add(new SelectListItem { Text = "Ngừng Hoạt Động", Value = "false" });
            ViewBag.data = trangThai;
            ViewBag.chucvu = _chucVuKhoBus.LoadChucVu();

            List<SelectListItem> admin = new List<SelectListItem>();
            admin.Add(new SelectListItem { Text = "Chủ của hàng", Value = "3" });
            ViewBag.Admin = admin;
            ViewBag.thongTinNhanVien = _nhanVienKhoBus.LoadDanhSachNhanVienTheoMa(id).ToList();
      
            return View(ViewBag.thongTinNhanVien);
        }
        public ActionResult Create()
        {
            ViewBag.chucvu = _chucVuKhoBus.LoadChucVu();
            return View();
        }
      
        [HttpPost]
        public async Task<ActionResult> Create(NhanVienViewModel nhanVien, HttpPostedFileBase avatar)
        { 
            if (avatar != null && avatar.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Content/image/user"),
                                               Path.GetFileName(avatar.FileName));
                    avatar.SaveAs(path);
                    nhanVien.avatar = avatar.FileName;
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                nhanVien.avatar = "default.png";
            }

            try
            {
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Content/client/template/themnhanvien.html"));

                content = content.Replace("{{TenNhanVien}}", nhanVien.tenNhanVien);
                content = content.Replace("{{Username}}", nhanVien.userName);
                content = content.Replace("{{Password}}", nhanVien.password);

                String subject = "Thông tin từ cửa hàng BK Computer!!!";
                SentMail.Sent(subject, nhanVien.email, "csms.project.fpt@gmail.com", "T12345678", content);

                await _nhanVienKhoBus.Create(nhanVien);
                SetAlert("Đã thêm nhân viên thành công!!!", "success");
            }
            catch
            {
                TempData["nhanVien"] = nhanVien;
                SetAlert("Đã xảy ra lỗi! Bạn hãy thêm lại", "error");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            List<SelectListItem> trangThai = new List<SelectListItem>();
            trangThai.Add(new SelectListItem { Text = "Đang Hoạt Động", Value = "true" });
            trangThai.Add(new SelectListItem { Text = "Ngừng Hoạt Động", Value = "false" });
            ViewBag.data = trangThai;
            ViewBag.chucvu = _chucVuKhoBus.LoadChucVu();

            List<SelectListItem> admin = new List<SelectListItem>();
            admin.Add(new SelectListItem { Text = "Chủ của hàng", Value = "3" });
            ViewBag.Admin = admin;
            return View(_nhanVienKhoBus.LoadDanhSachNhanVienTheoMa(id).ToList());
        }
       
        [HttpPost]
        public async Task<ActionResult> Edit(int id, NhanVienViewModel nhanVien, HttpPostedFileBase avatar)
        {
            if (avatar != null && avatar.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Content/image/user"),
                                               Path.GetFileName(avatar.FileName));
                    avatar.SaveAs(path);
                    nhanVien.avatar = avatar.FileName;
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
               // nhanVien.avatar = "default.png";
                nhanVien.avatar = nhanVien.checkImage;
            }

            if(id == 1)
            {
                nhanVien.trangThai = true;
                nhanVien.maChucVu = 3;
            }
             //Get nhân viên muốn update (find by ID)
            NhanVien edit = (NhanVien)await _nhanVienKhoBus.Find(id);
            if (edit == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Access Update from Business
                try
                {
                    await _nhanVienKhoBus.Update(nhanVien, edit);
                    SetAlert("Đã cập nhật nhân viên thành công!!!", "success");

                }
                catch
                {
                    TempData["nhanVien"] = nhanVien;
                    SetAlert("Đã xảy ra lỗi! Bạn hãy cập nhật lại", "error");
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Detail()
        {
            return View();
        }
    }
}

Source code/C-SMS/Areas/Admin/Views/NhanVien/Create.cshtml
@model Common.ViewModels.NhanVienViewModel
@{
    ViewBag.Title = "Thêm nhân viên";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}
<link href="~/Content/assets/css/generalMessageError.css" rel="stylesheet" />
<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Nhân Viên</h2>
        <div class="breadcrumb-wrapper hidden-xs">
            <button class="btn btn-lg btn-success btn-xs btn-push" id="submit"><i class="glyphicon glyphicon-save"></i> Lưu</button>
            <button class="btn btn-lg btn-success btn-xs btn-push" onclick="@("window.location.href='" + @Url.Action("Index", "NhanVien") + "'"); ">
                <i class="glyphicon glyphicon-arrow-left"></i> Quay lại
            </button>
          
        </div>
    </div>

    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <!-- Start input fields - basic form -->
                <div class="panel rounded shadow">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h3 class="panel-title">@ViewBag.Title</h3>
                        </div>

                        <div class="clearfix"></div>
                    </div><!-- /.panel-heading -->

                    <div class="panel-body no-padding">
                        @using (Html.BeginForm("Create", "NhanVien", FormMethod.Post, new { id = "basic-validate", enctype = "multipart/form-data" }))
                        {
                            <div class="form-body">

                                <div class="form-group">
                                    <label class="control-label">Tên Nhân Viên</label>
                                    <input type="text" name="tennhanvien" class="form-control rounded" maxlength="50" required />
                                </div>

                                <div class="form-group">
                                    <label class="control-label">Tên Đăng Nhập</label>
                                    <input type="text" id="username" name="username" class="form-control rounded" maxlength="100" required />
                                    <h3 style="margin-top:0%" hidden class="error  notifyinputUserName messageErrorinputUserName">User name đã tồn tại!</h3>
                                    <input type="hidden" id="checkusername" name="checkusername" class="form-control rounded" />
                                </div>

                                <div class="form-group">
                                    <label class="control-label">Mật Khẩu</label>
                                    <input type="password" name="password" class="form-control rounded" maxlength="15" required />
                                </div>

                                <div class="form-group">
                                    <label class="control-label">Email   </label>
                                    <input type="text" id="email" name="email" class="form-control rounded" maxlength="30" />
                                    <h3 style="margin-top:0%" hidden class="error  notifyinputEmail messageErrorinputEmail">Email đã tồn tại!</h3>
                                    <input type="hidden" id="checkemail" name="checkemail" class="form-control rounded" />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Số Điện Thoại</label>
                                    <input type="text" id="sodienthoai" name="sodienthoai" class="form-control rounded" maxlength="15" />
                                    <h3 style="margin-top:0%" hidden class="error  notifyinputPhone messageErrorinputPhone">Số điện thoại đã tồn tại!</h3>
                                    <input type="hidden" id="checkphone" name="checkphone" class="form-control rounded" />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Địa Chỉ</label>
                                    <input type="text" name="diachi" class="form-control rounded" maxlength="100" />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">CMND</label>
                                    <input type="text" id="cmnd" name="cmnd" class="form-control rounded" maxlength="10" />
                                    <h3 style="margin-top:0%" hidden class="error  notifyinputCMND messageErrorinputCMND">CMND đã tồn tại!</h3>
                                    <input type="hidden" id="checkcmnd" name="checkcmnd" class="form-control rounded" />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Chức Vụ</label>
                                  
                                     @Html.DropDownList("machucvu", new SelectList(ViewBag.chucvu, "Value", "Text"), new { @class = "form-control rounded" })
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label">Hình Đại Diện</label>
                                    <p id="error1" style="display:none; color:#FF0000;">
                                        Định dạng ảnh không hợp lệ! Định dạng hình ảnh phải là: JPG, JPEG, PNG.
                                    </p>
                                    <p id="error2" style="display:none; color:#FF0000;">
                                        Kích thước file hình phải nhỏ hơn 1MB.
                                    </p>
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="fileinput-preview thumbnail" name="avatar" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                                        <div>
                                            <span class="btn btn-info btn-file">
                                                <span class="fileinput-new">Chọn hình ảnh</span><span class="fileinput-exists">Thay đổi</span>
                                                <input type="file" name="avatar" id="fileUpload" accept="image/*">
                                            </span>
                                            <a href="#" class="btn btn-danger fileinput-exists" id="xoa" data-dismiss="fileinput">Xóa</a>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.form-body -->
                        }

                    </div><!-- /.panel-body -->
                </div><!-- /.panel -->
                <!--/ End input fields - basic form-->
            </div><!-- /.col-md-6 -->
        </div>
    </div>
</section>
<script src="~/Scripts/bootstrap.min.js"></script>
<script>
    $('#submit').click(function () {
        $('#basic-validate').submit();
    });
</script>

<script>
    $("#username").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { username: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputUserName").text("User name đã tồn tại!");
                $(".notifyinputUserName").slideDown(250).removeClass("hidden");
                var str1 = document.getElementById("username").value;
                $('#checkusername').val(str1);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputUserName").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });

    $("#email").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { email: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputEmail").text("Email đã tồn tại!");
                $(".notifyinputEmail").slideDown(250).removeClass("hidden");
                var str2 = document.getElementById("email").value;
                $('#checkemail').val(str2);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputEmail").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });

    $("#sodienthoai").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { sodienthoai: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputPhone").text("Số điện thoại đã tồn tại!");
                $(".notifyinputPhone").slideDown(250).removeClass("hidden");
                var str3 = document.getElementById("sodienthoai").value;
                $('#checkphone').val(str3);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputPhone").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });

    $("#cmnd").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { cmnd: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputCMND").text("CMND đã tồn tại!");
                $(".notifyinputCMND").slideDown(250).removeClass("hidden");
                var str4 = document.getElementById("cmnd").value;
                $('#checkcmnd').val(str4);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputCMND").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });
</script>

<script>
    var a = 0;
    //binds to onchange event of your input field
    $('#fileUpload').bind('change', function () {
        if ($('input:submit').attr('disabled', false)) {
            // $('input:submit').attr('disabled', true);
            document.getElementById("submit").disabled = true;
        }
        var ext = $('#fileUpload').val().split('.').pop().toLowerCase();
        if ($.inArray(ext, ['png', 'jpg', 'jpeg']) == -1) {
            $('#error1').slideDown("slow");
            $('#error2').slideUp("slow");
            a = 0;
        } else {
            var picsize = (this.files[0].size);
            if (picsize > 1000000) {
                $('#error2').slideDown("slow");
                a = 0;
            } else {
                a = 1;
                $('#error2').slideUp("slow");
            }
            $('#error1').slideUp("slow");
            if (a == 1) {
                //$('input:submit').attr('disabled', false);
                document.getElementById("submit").disabled = false;
            }
        }
    });

    $("#xoa").on('click keyup input propertychange paste change', function () {
        $("#error1").addClass("hidden");
        $("#error2").addClass("hidden");
        document.getElementById("submit").disabled = false;
    });
</script>

Source code/C-SMS/Areas/Admin/Views/NhanVien/DanhSachNhanVien.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Common.ViewModels.NhanVienViewModel>

<div class="table-responsive">
    <table class="table table-bordered table-middle table-lilac">
        <thead>
            <tr>
                <th class="text-center" style="width: 20%;">Nhân viên</th>
                <th class="text-center" style="width: 12%;">Tên đăng nhập</th>
                <th class="text-center" style="width: 12%;">Chức vụ</th>
                <th class="text-center" style="width: 12%;">Số điện thoại</th>
                <th class="text-center" style="width: 12%;">Email</th>
                <th class="text-center" style="width: 12%;">Trạng thái</th>
                <th class="text-center" style="width: 10%;">Hành động</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="border-warning">

                    <td>
                        <img src="~/Content/image/user/@item.avatar" width="50" height="50" class="img-circle img-bordered-theme">
                        <span>@item.tenNhanVien</span>
                    </td>
                    <td>@item.userName</td>
                    <td>@item.tenChucVu</td>
                    <td>@item.soDienThoai</td>
                    <td>@item.email</td>
                    @if (@item.trangThai == true)
                    {
                        <td>Đang hoạt động</td>
                        <td>
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Thao tác</button>
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="@Url.Action("Detail", new { id = item.maNhanVien })"><i class="fa fa-eye"></i> Xem</a></li>
                                    <li><a href="@Url.Action("Edit", new { id = item.maNhanVien })"><i class="fa fa-edit"></i> Sửa</a></li>
                                </ul>
                            </div>
                        </td>

                    }
                    else
                    {
                        <td>Ngừng hoạt động</td>
                        <td>
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Thao tác</button>
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="@Url.Action("Detail", new { id = item.maNhanVien })"><i class="fa fa-eye"></i> Xem</a></li>

                                </ul>
                            </div>
                        </td>

                    }

                </tr>
            }
        </tbody>
    </table>
</div>

<div class="pull-left" style="padding-top:20px">
    <h4 class="panel-title">Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount </h4>
</div>
<div class="pull-right">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>

Source code/C-SMS/Areas/Admin/Views/NhanVien/Detail.cshtml
@{
    ViewBag.Title = "Thông tin nhân viên";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}

<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Nhân Viên</h2>
        <div class="breadcrumb-wrapper hidden-xs">
           
            <button class="btn btn-lg btn-success btn-xs btn-push" onclick="@("window.location.href='" + @Url.Action("Create", "NhanVien") + "'"); ">
                <i class="glyphicon glyphicon-edit"></i>
                Tạo mới nhân viên
            </button>

            <button class="btn btn-lg btn-success btn-xs btn-push" onclick="@("window.location.href='" + @Url.Action("Index", "NhanVien") + "'"); ">
                <i class="glyphicon glyphicon-arrow-left"></i> Quay lại
            </button>

        </div>
    </div>

    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <!-- Start input fields - basic form -->
                <div class="panel rounded shadow">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h3 class="panel-title">@ViewBag.Title</h3>
                        </div>

                        <div class="clearfix"></div>
                    </div><!-- /.panel-heading -->

                    <div class="panel-body no-padding">

                        <div class="form-body">
                            @{Html.RenderAction("ThongTinNhanVien", "NhanVien");}

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/Scripts/bootstrap.min.js"></script>

Source code/C-SMS/Areas/Admin/Views/NhanVien/Edit.cshtml
@model IList<Common.ViewModels.NhanVienViewModel>

@{
    ViewBag.Title = "Sửa thông tin nhân viên";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}
<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Nhân Viên</h2>
        <div class="breadcrumb-wrapper hidden-xs">
            <button class="btn btn-lg btn-success btn-xs btn-push" id="submit"><i class="glyphicon glyphicon-save"></i> Lưu</button>

            <button class="btn btn-lg btn-success btn-xs btn-push" onclick="@("window.location.href='" + @Url.Action("Create", "NhanVien") + "'"); ">
                <i class="glyphicon glyphicon-edit"></i>
                Tạo mới nhân viên
            </button>

            <button class="btn btn-lg btn-success btn-xs btn-push" onclick="@("window.location.href='" + @Url.Action("Index", "NhanVien") + "'"); ">
                <i class="glyphicon glyphicon-arrow-left"></i> Quay lại
            </button>

        </div>
    </div>

    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <!-- Start input fields - basic form -->
                <div class="panel rounded shadow">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h3 class="panel-title">@ViewBag.Title</h3>
                        </div>

                        <div class="clearfix"></div>
                    </div><!-- /.panel-heading -->

                    <div class="panel-body no-padding">
                       @using (Html.BeginForm("Edit", "NhanVien", FormMethod.Post, new { id = "basic-validate", enctype = "multipart/form-data" }))
                       {
                            <div class="form-body">
                                @{Html.RenderAction("ThongTinNhanVien", "NhanVien");}

                            </div>
                           
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/Scripts/bootstrap.min.js"></script>
<script>
    $('#submit').click(function () {
        $('#basic-validate').submit();
    });
</script>

<script>
    $("#username").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { username: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputUserName").text("User name đã tồn tại!");
                $(".notifyinputUserName").slideDown(250).removeClass("hidden");
                var str1 = document.getElementById("username").value;
                $('#checkusername').val(str1);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputUserName").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });

    $("#email").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { email: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputEmail").text("Email đã tồn tại!");
                $(".notifyinputEmail").slideDown(250).removeClass("hidden");
                var str2 = document.getElementById("email").value;
                $('#checkemail').val(str2);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputEmail").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });

    $("#sodienthoai").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { sodienthoai: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputPhone").text("Số điện thoại đã tồn tại!");
                $(".notifyinputPhone").slideDown(250).removeClass("hidden");
                var str3 = document.getElementById("sodienthoai").value;
                $('#checkphone').val(str3);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputPhone").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });

    $("#cmnd").on('keyup input propertychange paste change', function () {
        $.getJSON('@Url.Action("CheckUserName", "NhanVien")', { cmnd: $(this).val() }, function (data) {
            if (data.isDuplicate) {
                $(".messageErrorinputCMND").text("CMND đã tồn tại!");
                $(".notifyinputCMND").slideDown(250).removeClass("hidden");
                var str4 = document.getElementById("cmnd").value;
                $('#checkcmnd').val(str4);
                document.getElementById("submit").disabled = true;
            }
            else {
                $(".notifyinputCMND").addClass("hidden");
                document.getElementById("submit").disabled = false;
            }
        });
    });
</script>

<script>
    var a = 0;
    //binds to onchange event of your input field
    $('#fileUpload').bind('change', function () {
        if ($('input:submit').attr('disabled', false)) {
            // $('input:submit').attr('disabled', true);
            document.getElementById("submit").disabled = true;
        }
        var ext = $('#fileUpload').val().split('.').pop().toLowerCase();
        if ($.inArray(ext, ['png', 'jpg', 'jpeg']) == -1) {
            $('#error1').slideDown("slow");
            $('#error2').slideUp("slow");
            a = 0;
        } else {
            var picsize = (this.files[0].size);
            if (picsize > 1000000) {
                $('#error2').slideDown("slow");
                a = 0;
            } else {
                a = 1;
                $('#error2').slideUp("slow");
            }
            $('#error1').slideUp("slow");
            if (a == 1) {
                //$('input:submit').attr('disabled', false);
                document.getElementById("submit").disabled = false;
            }
        }
    });

    $("#xoa").on('click keyup input propertychange paste change', function () {
        $("#error1").addClass("hidden");
        $("#error2").addClass("hidden");
        document.getElementById("submit").disabled = false;
    });
</script>
  