Source code/C-SMS/Areas/Admin/Controllers/BaoCaoBanHangController.cs
using Business.Implements;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using System.Web.UI.WebControls;
using System.Web.UI;
using WebBanHang.Reports;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class BaoCaoBanHangController : BaseController
    {
        //
        // GET: /Admin/BaoCaoBanHang/

        static DateTime _dateFrom;
        static DateTime _dateTo;

        readonly BaoCaoBanHangBusiness _baoCaoBanHangBUS = new BaoCaoBanHangBusiness();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DanhSachBaoCaoBanHang(string dateFrom, string dateTo)
        {
            _dateFrom = Convert.ToDateTime(dateFrom);
            if (_dateFrom == default(DateTime))
            {
                _dateFrom = Convert.ToDateTime("1/" + DateTime.Now.Month + "/" + DateTime.Now.Year);
            }
            _dateTo = Convert.ToDateTime(dateTo);
            if (_dateTo == default(DateTime))
            {
                _dateTo = DateTime.Now;
            }
            return View(_baoCaoBanHangBUS.ListView(HomeController.userName, _dateFrom, _dateTo).ToList());
        }

        public ActionResult XuatFilePDF()
        {
            try
            {
                ReportDocument rd = new ReportDocument();
                rd.Load(Path.Combine(Server.MapPath("~/Reports/BaoCaoBanHangRP.rpt")));
                rd.SetDataSource(_baoCaoBanHangBUS.ListView(HomeController.userName, _dateFrom, _dateTo).ToList());
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                rd.SetParameterValue("txtDateFrom", _dateFrom.ToString("dd/MM/yyyy"));
                rd.SetParameterValue("txtDateTo", _dateTo.ToString("dd/MM/yyyy"));
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/pdf", "BaoCaoBanHangRP.pdf");
            }
            catch
            {
                SetAlert("Dữ liệu không có! Bạn hãy lọc lại dữ liệu", "error");
                return RedirectToAction("Index");
            }
            
        }

        public ActionResult XuatFileEXE()
        {
            //GridView gv = new GridView();
            //gv.DataSource = _baoCaoBanHangBUS.ListView(HomeController.nhanVienCode, _dateFrom, _dateTo).ToList();

            //gv.DataBind();
            //Response.ClearContent();
            //Response.Buffer = true;
            //Response.AddHeader("content-disposition", "attachment; filename=CustomerReport.xls");
            //Response.ContentType = "application/ms-excel";
            //Response.Charset = "";
            //StringWriter sw = new StringWriter();
            //HtmlTextWriter htw = new HtmlTextWriter(sw);
            //gv.RenderControl(htw);
            //Response.Output.Write(sw.ToString());
            //Response.Flush();
            //Response.End();

            //return RedirectToAction("Index");
           

            try
            {
                ReportDocument rd = new ReportDocument();
                rd.Load(Path.Combine(Server.MapPath("~/Reports/BaoCaoBanHangRP.rpt")));
                rd.SetDataSource(_baoCaoBanHangBUS.ListView(HomeController.userName, _dateFrom, _dateTo).ToList());
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                rd.SetParameterValue("txtDateFrom", _dateFrom.ToString("dd/MM/yyyy"));
                rd.SetParameterValue("txtDateTo", _dateTo.ToString("dd/MM/yyyy"));
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.ExcelWorkbook);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/xls", "BaoCaoBanHangRP.xls");
            }
            catch
            {
                SetAlert("Dữ liệu không có! Bạn hãy lọc lại dữ liệu", "error");
                return RedirectToAction("Index");
            }
        }
    }
}

Source code/C-SMS/Areas/Admin/Views/BaoCaoBanHang/DanhSachBaoCaoBanHang.cshtml
@using PagedList.Mvc
@model List<Common.ViewModels.BaoCaoBanHangViewModel>
@using Common.Ultil

<br />
<table class="table table-bordered table-middle table-lilac">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Ngày bán")
            </th>
            <th>
                @Html.DisplayName("Số hoá đơn")
            </th>
            <th>
                @Html.DisplayName("Tổng tiền (VNĐ)")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            FormatNumber number = new FormatNumber();
            <tr class="border-warning">
                <td>@item.ngayBan.ToString("dd/MM/yyyy")</td>
                <td>@item.soDonHang</td>
                <td>@number.FormatNumbers(@item.tongTien.ToString())</td>
            </tr>
        }
    </tbody>
</table>

Source code/C-SMS/Areas/Admin/Views/BaoCaoBanHang/Index.cshtml
@model List<Common.ViewModels.BaoCaoBanHangViewModel>
@using Common.ViewModels
@{
    ViewBag.Title = "Báo cáo bán hàng";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}

<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Báo cáo doanh thu</h2>
        <div class="breadcrumb-wrapper hidden-xs">
            <div class="input-group-btn">
                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Xuất ra file</button>
                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li><a href="@Url.Action("XuatFilePDF", "BaoCaoBanHang")">Xuất file PDF</a></li>
                    <li><a href="@Url.Action("XuatFileEXE", "BaoCaoBanHang")">Xuất file Excel</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="panel rounded shadow">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h3 class="panel-title">Báo cáo doanh thu bán hàng</h3>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="form-body">
                            @using (Ajax.BeginForm("DanhSachBaoCaoBanHang", "BaoCaoBanHang", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "list", HttpMethod = "Get" }, new { id = "filter_div" }))
                            {
                                <div class="form-group">
                                    <div class="col-md-6">
                                        <label>Từ ngày</label>
                                        <input type="date" id="dateFrom" name="dateFrom" data-date-format="dd/mm/yyyy" required class="form-control rounded" />
                                    </div>
                                    <div class="col-md-6">
                                        <label>Đến ngày</label>
                                        <div class="input-group">
                                            <input type="date" id="dateTo" name="dateTo" required class="form-control rounded" />
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>

                            }
                            <div id="list">
                                @{Html.RenderAction("DanhSachBaoCaoBanHang", "BaoCaoBanHang");}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/Scripts/bootstrap.min.js"></script>