Source code/C-SMS/Controllers/PhieuDatHangController.cs
using Business.Implements;
using Common.Models;
using Common.Ultil;
using Common.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace WebBanHang.Controllers
{
    public class PhieuDatHangController : BaseController
    {
        readonly HangHoaBusiness _hangHoaBus = new HangHoaBusiness();
        readonly PhieuDatHangBusiness _phieuDatHangBus = new PhieuDatHangBusiness();
        readonly ChiTietPhieuDatHangBusiness _chiTietPhieuDatHangBus = new ChiTietPhieuDatHangBusiness();
        private const string CartSession = "CartSession";
        // GET: PhieuDatHang
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<PhieuDatHangViewModel>();
            if (cart != null)
            {
                list = (List<PhieuDatHangViewModel>)cart;
            }
            return View(list);
        }

        public ActionResult DatHang(int maHangHoa, int soLuong)
        {
            var product = _hangHoaBus.ViewDetail(maHangHoa);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<PhieuDatHangViewModel>)cart;
                if (list.Exists(x => x.maHangHoa == maHangHoa))
                {

                    foreach (var item in list)
                    {
                        if (item.maHangHoa == maHangHoa)
                        {
                            item.soLuong += soLuong;
                        }
                    }
                }
                else
                {
                    //tạo mới đối tượng cart item
                    var item = new PhieuDatHangViewModel();
                    item.maHangHoa = product.MaHangHoa;
                    item.soLuong = soLuong;
                    item.tenHangHoa = product.TenHangHoa;
                    item.hinhAnh = product.HinhAnh;
                    item.giaBan = product.GiaBan;
                    item.giamGia = product.GiamGia;
                    list.Add(item);
                }
                //Gán vào session
                Session[CartSession] = list;
            }
            else
            {
                //tạo mới đối tượng cart item
                var item = new PhieuDatHangViewModel();
                item.maHangHoa = product.MaHangHoa;
                item.soLuong = soLuong;
                item.tenHangHoa = product.TenHangHoa;
                item.hinhAnh = product.HinhAnh;
                item.giaBan = product.GiaBan;
                item.giamGia = product.GiamGia;
                var list = new List<PhieuDatHangViewModel>();
                list.Add(item);
                //Gán vào session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAll()
        {
            Session[CartSession] = null;
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var sessionCart = (List<PhieuDatHangViewModel>)Session[CartSession];
            sessionCart.RemoveAll(x => x.maHangHoa == id);
            Session[CartSession] = sessionCart;
            return RedirectToAction("Index");
        }

        public ActionResult Update(FormCollection fc)
        {
            string[] quatities = fc.GetValues("soLuong");
            List<PhieuDatHangViewModel> cart = (List<PhieuDatHangViewModel>)Session[CartSession];
            for (int i = 0; i < cart.Count; i++)
                cart[i].soLuong = Convert.ToInt32(quatities[i]);
            Session[CartSession] = cart;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ThanhToan()
        {
            List<SelectListItem> hinhThucThanhToan = new List<SelectListItem>();
            hinhThucThanhToan.Add(new SelectListItem { Text = "Thanh toán tại cửa hàng" });
            hinhThucThanhToan.Add(new SelectListItem { Text = "Thanh toán tại nhà" });
            ViewBag.hinhThucThanhToan = hinhThucThanhToan;
            var cart = Session[CartSession];
            var list = new List<PhieuDatHangViewModel>();
            if (cart != null)
            {
                list = (List<PhieuDatHangViewModel>)cart;
            }
            return View(list);
        }

        [HttpPost]
        public async Task<ActionResult> ThanhToan(PhieuDatHangViewModel datHang)
        {
            var phieuDatHang = new PhieuDatHang();
            phieuDatHang.NgayDat = DateTime.Now;
            phieuDatHang.TenKhachHang = datHang.tenKhachHang;
            phieuDatHang.SoDienThoai = datHang.soDienThoai;
            phieuDatHang.Diachi = datHang.diaChi;
            phieuDatHang.Email = datHang.email;
            phieuDatHang.HinhThucThanhToan = datHang.hinhThucThanhToan;
            phieuDatHang.Ghichu = datHang.ghiChu;
            phieuDatHang.NgayChinhSua = DateTime.Now;
            phieuDatHang.DaThanhToan = false;
            phieuDatHang.DaXacNhan = false;
            phieuDatHang.TrangThai = true;

            try
            {
                var soPhieuBanHang = _phieuDatHangBus.Insert(phieuDatHang);
                var cart = (List<PhieuDatHangViewModel>)Session[CartSession];
                decimal total = 0;
                foreach (var item in cart)
                {
                    var chiTietPhieuDatHang = new ChiTietPhieuDatHang();
                    chiTietPhieuDatHang.MaHangHoa = item.maHangHoa;
                    chiTietPhieuDatHang.SoPhieuDatHang = soPhieuBanHang;
                    chiTietPhieuDatHang.SoLuong = item.soLuong;
                    if (item.giamGia <= 0)
                    {
                        chiTietPhieuDatHang.Gia = item.giaBan;
                        chiTietPhieuDatHang.ThanhTien = item.giaBan * item.soLuong;
                        total += (item.giaBan * item.soLuong);
                    }
                    else
                    {
                        chiTietPhieuDatHang.Gia = item.giamGia;
                        chiTietPhieuDatHang.ThanhTien = item.giamGia * item.soLuong;
                        total += (item.giamGia * item.soLuong);
                    }
                                   
                    _chiTietPhieuDatHangBus.Insert(chiTietPhieuDatHang);

                   // total += (item.giaBan * item.soLuong);
                }
                phieuDatHang.TongTien = total;
                _phieuDatHangBus.UpdateTongTien(phieuDatHang);

                string content = System.IO.File.ReadAllText(Server.MapPath("~/Content/client/template/neworder.html"));
                content = content.Replace("{{CustomerName}}", datHang.tenKhachHang);
                content = content.Replace("{{Phone}}", datHang.soDienThoai);
                content = content.Replace("{{Email}}", datHang.email);
                content = content.Replace("{{Address}}", datHang.diaChi);
                content = content.Replace("{{Total}}", total.ToString("N0"));
                content = content.Replace("{{Method}}", datHang.hinhThucThanhToan);
                content = content.Replace("{{Note}}", datHang.ghiChu);

                String subject = "Đơn hàng mới từ BK Computer!!!";
                //String message = "Hello " + phieuDatHang.TenKhachHang + "!!! <br/><br/>Your ID:<br/>Your password: <br/>Please go to <a href='http://localhost:54962/'>here</a> to change this automatic password!!!";
                SentMail.Sent(subject, datHang.email, "csms.project.fpt@gmail.com", "T12345678", content);
            }
            catch (Exception)
            {
                SetAlert("Đã xảy ra lỗi trong quá trình đặt hàng! Vui lòng thực hiện lại!!!", "error");
                return RedirectToAction("ThanhToan");
            }
            Session[CartSession] = null; 
            return RedirectToAction("ThongBaoThanhCong");
        }

        public ActionResult ThongBaoThanhCong()
        {
            return View();
        }
    }
}

Source code/C-SMS/Views/PhieuDatHang/Index.cshtml
@model List<Common.ViewModels.PhieuDatHangViewModel>
@using Common.Ultil
@{
    ViewBag.Title = "Đặt Hàng";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<div id="vnt-container" class="container">
    <div class="navation row"><a href="#" class="home">Trang chủ</a> <span>&nbsp;/&nbsp;</span><span>Giỏ hàng</span></div>
    <section class="newshot-block row">
        <div class="col-md-6 col-sm-6 col-xs-12 block">
            <div class="block-inner">
                <a class='table' href='#' target='_self' title='LG V10: Điện thoại thời trang'>
                    <div class='inner'>
                        <h3>LG V10: Điện thoại thời trang</h3>
                        <span></span>
                        <i class='fa fa-angle-right'></i>
                    </div>
                </a><figure>
                    <div class="frame"><span> </span></div>
                    <img src="~/Content/client/vnt_upload/weblink/banner/v10_1.png" alt="LG V10: Điện thoại thời trang" />
                </figure>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12 block last">
            <div class="block-inner">
                <a class='table' href='#' target='_self' title='Chuyên các dòng Samsung độc nhất'>
                    <div class='inner'>
                        <h3>Chuyên các dòng Samsung độc nhất</h3>
                        <span></span>
                        <i class='fa fa-angle-right'></i>
                    </div>
                </a><figure><div class="frame"><span> </span></div><img src="~/Content/client/vnt_upload/weblink/banner/DSC_8642.jpg" alt="Chuyên các dòng Samsung độc nhất" /> </figure>
            </div>
        </div>
    </section>

    <div id="vnt-content">

        <div class="row">
            <div class="box_mid">
                <div class="mid-title">
                    <div class="titleL">Thông tin đặt hàng</div>
                    <div class="titleR"></div>
                    <div class="clear"></div>
                </div>
                <div class="mid-content">

                    <script language="JavaScript" type="text/javascript">

                        jQuery(document).ready(function () {
                            //valid form
                            jQuery('#installmentForm').bootstrapValidator({
                                message: 'This value is not valid',
                                feedbackIcons: {
                                    valid: 'glyphicon glyphicon-ok',
                                    invalid: 'glyphicon glyphicon-remove',
                                    validating: 'glyphicon glyphicon-refresh'
                                },
                                excluded: ':disabled',
                                fields: {
                                    'color_id': {
                                        validators: {
                                            notEmpty: {
                                                message: 'Vui lòng chọn màu sắc'
                                            },
                                        },
                                        trigger: 'change keyup',
                                    },
                                    'd_name': {
                                        validators: {
                                            notEmpty: {
                                                message: 'Không được để trống'
                                            }
                                        }
                                    },
                                    'd_phone': {
                                        validators: {
                                            notEmpty: {
                                                message: 'Không được để trống'
                                            },
                                            regexp: {
                                                regexp: /^[0-9]+$/,
                                                message: 'Chỉ dùng số'
                                            },
                                            stringLength: {
                                                min: 10,
                                                max: 11,
                                                message: '10 hoặc 11 số'
                                            }
                                        }
                                    },
                                    'd_email': {
                                        validators: {
                                            notEmpty: {
                                                message: 'Không được để trống'
                                            },
                                            emailAddress: {
                                                message: 'Không đúng định dạng email'
                                            }
                                        }
                                    },
                                }
                            });


                            $("input[id='pick-label']").click(function () {
                                $("#city").hide();
                                $("#address").hide();
                                $("#address_store").show();

                            });

                            $("input[id='delivery-label']").click(function () {
                                $("#city").show();
                                $("#address").show();
                                $("#address_store").hide();

                            });
                        });
                    </script>
                    <div class="order">
                        @using (Ajax.BeginForm("Update", "PhieuDatHang", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "list", HttpMethod = "Get" }, new { id = "filter_div" }))
                        {
                            <div class="section group">
                                @if (Model.Count > 0)
                                {
                                    <table class="table" id="productTable">
                                        <thead>
                                            <tr>
                                                <td> <label>Mã Sản Phẩm</label></td>
                                                <td> <label>Sản Phẩm </label></td>
                                                <td> <label>Hình Ảnh</label> </td>
                                                <td> <label>Số lượng </label>  </td>
                                                <td> <label>Đơn giá</label> </td>
                                                <td> <label>Thành tiền</label> </td>
                                                <td></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                FormatNumber number = new FormatNumber();
                                                <tr>
                                                    <td>@item.maHangHoa</td>
                                                    <td>@item.tenHangHoa</td>
                                                    <td><img src="~/Content/client/product/@item.hinhAnh" width="100" /></td>
                                                    <td><input type="text" id="soLuong" name="soLuong" value="@item.soLuong" class="form-control" style="width:50px" maxlength="3" onkeypress="return checkNumber(event, this)" /></td>

                                                    @if (@item.giamGia <= 0)
                                                    {
                                                        <td>@number.FormatNumbers(@item.giaBan.ToString()) VND</td>
                                                        <td>@number.FormatNumbers((@item.giaBan * @item.soLuong).ToString()) VND</td>
                                                    }
                                                    else
                                                    {
                                                        <td>@number.FormatNumbers(@item.giamGia.ToString()) VND</td>
                                                        <td>@number.FormatNumbers((@item.giamGia * @item.soLuong).ToString()) VND</td>
                                                    }
                                                    <td>
                                                        <button class=" btn-danger">
                                                            <a href="@Url.Action("Delete", new { id = item.maHangHoa })" class=" btn-danger"> Xóa</a>
                                                        </button>

                                                    </td>
                                                </tr>
                                            }
                                            <tr>

                                                <td colspan="7">
                                                    <label class="col-sm-9 control-label">Tổng tiền (VNĐ)</label>
                                                    <div class="col-sm-2">
                                                        <input type="text" id="tongTien" name="tongTien" class="form-control" disabled="disabled">
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                }
                                else
                                {
                                    <div class="alert alert-danger fade in">
                                        <span><i class="fa fa-bullhorn" style="padding-right: 7px" aria-hidden="true"></i>Chưa có sản phẩm nào trong giỏ hàng</span>
                                    </div>
                                }
                            </div>
                        }
                        @if (Model.Count > 0)
                        {
                            <div style="text-align: center;">
                                <button class="btn btn-success" id="submit"> Cập nhật giỏ hàng </button>
                                <button class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'"); "> Tiếp tục mua hàng </button>
                                <button class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("DeleteAll", "PhieuDatHang") + "'"); "> Xóa giỏ hàng </button>
                                <button class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("ThanhToan", "PhieuDatHang") + "'"); "> Thanh toán </button>

                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>

<script>
    $(document).ready(function () {
        var amount;
        var total = 0.0;
        var row = document.getElementById('productTable').rows.length;
        for (var i = 1; i < row; i++) {
            amount = document.getElementById("productTable").rows[i].cells[5].innerHTML.replace(/,/gi, "");

            total += parseFloat(amount);
            $('#tongTien').val(formatNumber(parseFloat(total)));
        }
    })

    function formatNumber(num) {
        return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
    }
</script>

<script>
    function checkNumber(e, element) {
        var charcode = (e.which) ? e.which : e.keyCode;
        if (charcode > 31 && (charcode < 48 || charcode > 57)) {
            return false;
        }
        return true;
    }
</script>

<script>
    $('#submit').click(function () {
        $('#filter_div').submit();
    });
</script>

Source code/C-SMS/Views/PhieuDatHang/ThanhToan.cshtml
@model List<Common.ViewModels.PhieuDatHangViewModel>
@using Common.Ultil
@{
    ViewBag.Title = "Thanh Toán";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<div id="vnt-container" class="container">
    <div class="navation row"><a href="#" class="home">Trang chủ</a> <span>&nbsp;/&nbsp;</span><span>Giỏ hàng</span></div>
    <section class="newshot-block row">
        <div class="col-md-6 col-sm-6 col-xs-12 block">
            <div class="block-inner">
                <a class='table' href='#' target='_self' title='LG V10: Điện thoại thời trang'>
                    <div class='inner'>
                        <h3>LG V10: Điện thoại thời trang</h3>
                        <span></span>
                        <i class='fa fa-angle-right'></i>
                    </div>
                </a><figure>
                    <div class="frame"><span> </span></div>
                    <img src="~/Content/client/vnt_upload/weblink/banner/v10_1.png" alt="LG V10: Điện thoại thời trang" />
                </figure>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12 block last">
            <div class="block-inner">
                <a class='table' href='#' target='_self' title='Chuyên các dòng Samsung độc nhất'>
                    <div class='inner'>
                        <h3>Chuyên các dòng Samsung độc nhất</h3>
                        <span></span>
                        <i class='fa fa-angle-right'></i>
                    </div>
                </a><figure><div class="frame"><span> </span></div><img src="~/Content/client/vnt_upload/weblink/banner/DSC_8642.jpg" alt="Chuyên các dòng Samsung độc nhất" /> </figure>
            </div>
        </div>
    </section>

    <div id="vnt-content">

        <div class="row">
            <div class="box_mid">
                <div class="mid-title">
                    <div class="titleL">Thông tin đặt hàng</div>
                    <div class="titleR"></div>
                    <div class="clear"></div>
                </div>
                <div class="mid-content">

                    
                    <div class="order">
                       @using (Html.BeginForm("Update", "PhieuDatHang", FormMethod.Post, new { id = "filter_div" }))
                       {
                            <div class="section group">
                                @if (Model.Count > 0)
                                {
                                    <table class="table" id="productTable">
                                        <thead>
                                            <tr>
                                                <td> <label>Mã Sản Phẩm</label></td>
                                                <td> <label>Sản Phẩm </label></td>
                                                <td> <label>Hình Ảnh</label> </td>
                                                <td> <label>Số lượng </label>  </td>
                                                <td> <label>Đơn giá</label> </td>
                                                <td> <label>Thành tiền</label> </td>
                                                <td></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                FormatNumber number = new FormatNumber();
                                                <tr>
                                                    <td>@item.maHangHoa</td>
                                                    <td>@item.tenHangHoa</td>
                                                    <td><img src="~/Content/client/product/@item.hinhAnh" width="100" /></td>
                                                    <td><input type="text" id="soLuong" name="soLuong" value="@item.soLuong" class="form-control" style="width:50px" maxlength="3" onkeypress="return checkNumber(event, this)" /></td>

                                                    @if (@item.giamGia <= 0)
                                                    {
                                                        <td>@number.FormatNumbers(@item.giaBan.ToString()) VND</td>
                                                        <td>@number.FormatNumbers((@item.giaBan * @item.soLuong).ToString()) VND</td>
                                                    }
                                                    else
                                                    {
                                                        <td>@number.FormatNumbers(@item.giamGia.ToString()) VND</td>
                                                        <td>@number.FormatNumbers((@item.giamGia * @item.soLuong).ToString()) VND</td>
                                                    }
                                                    <td>
                                                        <button class=" btn-danger">
                                                            <a href="@Url.Action("Delete", new { id = item.maHangHoa })" class=" btn-danger"> Xóa</a>
                                                        </button>

                                                    </td>
                                                </tr>
                                            }
                                            <tr>

                                                <td colspan="7">
                                                    <label class="col-sm-9 control-label">Tổng tiền (VNĐ)</label>
                                                    <div class="col-sm-2">
                                                        <input type="text" id="tongTien" name="tongTien" class="form-control" readonly>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                }
                                else
                                {
                                    <div class="alert alert-danger fade in">
                                        <span><i class="fa fa-bullhorn" style="padding-right: 7px" aria-hidden="true"></i>Chưa có sản phẩm nào trong giỏ hàng</span>
                                    </div>
                                }
                            </div>
                        }
                        @if (Model.Count > 0)
                        {
                            <div style="text-align: center;">
                                <button class="btn btn-success" id="submit"> Cập nhật giỏ hàng </button>
                                <button class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'"); "> Tiếp tục mua hàng </button>
                                <button class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("DeleteAll", "PhieuDatHang") + "'"); "> Xóa giỏ hàng </button>
                                <button class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("ThanhToan", "PhieuDatHang") + "'"); "> Thanh toán </button>

                            </div>
                        }

                        <br />
                        @if (Model.Count > 0)
                        {
                            <div class="alert alert-success fade in">
                                <span><i class="fa fa-bullhorn" style="padding-right: 7px" aria-hidden="true"></i>VUI LÒNG NHẬP THÔNG TIN CỦA QUÝ KHÁCH (Nhập thông tin phải có dấu)</span>
                            </div>
                            <div class="section group">
                                <div class="col-md-12">
                                    @using (Html.BeginForm("ThanhToan", "PhieuDatHang", FormMethod.Post, new { id = "installmentForm" }))

                                    {
                                        <div class="form-group">
                                            <label>Người nhận</label>
                                            <input name="tenKhachHang" class="form-control" placeholder="Họ và tên của bạn (Bắt buộc)" required maxlength="200"/>
                                        </div>
                                        <div class="form-group">
                                            <label>Điện thoại</label>
                                            <input name="soDienThoai" class="form-control" placeholder="Số điện thoại của bạn (Bắt buộc)" required maxlength="15"/>
                                        </div>
                                        <div class="form-group">
                                            <label>Địa chỉ</label>
                                            <input name="diaChi" class="form-control" placeholder="Địa chỉ của bạn (Bắt buộc)" required maxlength="200"/>
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input name="email" class="form-control" />
                                        </div>

                                        <div class="form-group">
                                            <label>Hình thức thanh toán</label>
                                            @Html.DropDownList("hinhthucthanhtoan", new SelectList(ViewBag.hinhThucThanhToan, "Text", "Text"), new { @class = "form-control" })
                                        </div>

                                        <div class="form-group">
                                            <label>Ghi chú</label>
                                            <textarea name="ghichu" class="form-control" placeholder="Yêu cầu khác"> </textarea>
                                        </div>
                                        <div style="text-align: center;">
                                            <button type="submit" class="btn btn-success">Gửi đơn hàng</button>
                                        </div>

                                    }
                                </div>

                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>


<script>
    $(document).ready(function () {
        var amount;
        var total = 0.0;
        var row = document.getElementById('productTable').rows.length;
        for (var i = 1; i < row; i++) {
            amount = document.getElementById("productTable").rows[i].cells[5].innerHTML.replace(/,/gi, "");

            total += parseFloat(amount);
            $('#tongTien').val(formatNumber(parseFloat(total)));
        }
    })

    function formatNumber(num) {
        return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
    }
</script>

<script>
    $('#submit').click(function () {
        $('#filter_div').submit();
    });
</script>