Source code/C-SMS/Areas/Admin/Controllers/DatHangController.cs
using Business.Implements;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Threading.Tasks;
using Common.ViewModels;
using Common.Models;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class DatHangController :BaseController
    {
        //
        // GET: /Admin/BanHang/

        readonly PhieuDatHangBusiness _phieuDatHangBUS = new PhieuDatHangBusiness();
        readonly ChiTietPhieuDatHangBusiness _chiTietPhieuDatHangBus = new ChiTietPhieuDatHangBusiness();
        readonly HangHoaBusiness _hangHoaBus = new HangHoaBusiness();
        readonly NhanVienBusiness _nhanVienBus = new NhanVienBusiness();

        public ActionResult Index()
        {
            ViewBag.trangthai = new SelectList(new[]{ new { Value = "true", Text = "Hoàn thành" },
                                                    new { Value = "false", Text = "Đã hủy" }},
                                               "Value", "Text");

            return View();
        }

        public ActionResult Detail()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        //public ActionResult DanhSachPhieuDatHang(string searchString, int page = 1, int pageSize = 5)
        //{
        //    //if(!string.IsNullOrEmpty(searchString))
        //    //{
        //    //    return View(_phieuBanHangBUS.SearchDanhSachPhieuKiemKho(searchString, HomeController.nhanVienCode).ToPagedList(page, pageSize));
        //    //}

        //    return View(_phieuDatHangBUS.ListView(HomeController.nhanVienCode).ToPagedList(page, pageSize));

        //    //return View();
        //}

        public ActionResult DanhSachPhieuDatHang(string searchString, string trangthai, string dateFrom, string dateTo, int page = 1, int pageSize = 10)
        {
            return View(_phieuDatHangBUS.SearchDanhSachPhieuDatHang(searchString, trangthai, Convert.ToDateTime(dateFrom), Convert.ToDateTime(dateTo), HomeController.userName).ToPagedList(page, pageSize));
        }

        public ActionResult ThongTinPhieuDatHang(int id)
        {
            ViewBag.chiTietPhieuDatHang = _chiTietPhieuDatHangBus.danhSachPhieuDatHangTheoMa(id).ToList();
            ViewBag.phieuDatHang = _phieuDatHangBUS.thongTinPhieuDatHangTheoMa(id).ToList();
            return View();
        }

        public ActionResult LoadThongTinHangHoa(int id)
        {
            var result = _hangHoaBus.LayThongTinHangHoa(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }        

        public ActionResult Delete()
        {
            return View();
        }

        public ActionResult XacNhanNhanHang()
        {
            return View();
        }

        public ActionResult XacNhanThanhToan()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> XacNhanNhanHangs(int id)
        {
            var updatePhieuDatHang = _phieuDatHangBUS.LayPhieuDatHang(id);
            updatePhieuDatHang.DaXacNhan = true;

            await _phieuDatHangBUS.Update(updatePhieuDatHang);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> XacNhanThanhToans(int id)
        {
            var updatePhieuDatHang = _phieuDatHangBUS.LayPhieuDatHang(id);
            updatePhieuDatHang.DaThanhToan = true;

            await _phieuDatHangBUS.Update(updatePhieuDatHang);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult>  Deletes(int id)
        {
            PhieuDatHang deletePhieu = (PhieuDatHang)await _phieuDatHangBUS.Find(id);

            if(deletePhieu == null)
            {
                return HttpNotFound();
            }
            else
            {
                try
                {
                    await _phieuDatHangBUS.DeletePhieuDatHang(deletePhieu);

                    SetAlert("Đã hủy phiếu đặt hàng thành công!!!", "success");
                }
                catch
                {
                    SetAlert("Đã xảy ra lỗi! Bạn hãy hủy lại", "error");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

Source code/C-SMS/Areas/Admin/Views/DatHang/DanhSachPhieuDatHang.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Common.ViewModels.PhieuDatHangViewModel>
@using Common.Ultil
<script src="~/Scripts/Tho/phieudathangScripts.js"></script>

<br />
<table class="table table-bordered table-middle table-lilac">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Số phiếu")
            </th>
            <th>
                @Html.DisplayName("Ngày đặt")
            </th>
            <th>
                @Html.DisplayName("Tên khách hàng")
            </th>
            <th>
                @Html.DisplayName("Số điện thoại")
            </th>
            <th>
                @Html.DisplayName("Tổng tiền")
            </th>
            <th>
                @Html.DisplayName("Xác nhận")
            </th>
            <th>
                @Html.DisplayName("Thanh toán")
            </th>
            <th>
                @Html.DisplayName("Trạng thái")
            </th>
            <th class="width-10">
                Hành động
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            FormatNumber number = new FormatNumber();
            <tr style="text-align:center">
                <td>@item.soPhieuDatHang</td>
                <td>@item.ngayDat.ToString("dd/MM/yyyy")</td>
                <td>@item.tenKhachHang</td>
                <td>@item.soDienThoai</td>
                <td>@number.FormatNumbers(@item.tongTien.ToString())</td>

                @if (@item.trangThai == true)
                {
                    if (@item.daXacNhan == true && @item.daThanhToan == true)
                    {
                        <td>Đã xác nhận</td>
                        <td>Đã thanh toán</td>
                        <td>Hoàn thành</td>
                        <td>
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Thao tác</button>
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="@Url.Action("Detail", new { id = item.soPhieuDatHang })"><i class="fa fa-eye"></i> Xem</a></li>
                                </ul>
                            </div>
                        </td>
                    }
                    if (@item.daXacNhan == false && @item.daThanhToan == true)
                    {
                        <td>Chưa xác nhận</td>
                        <td>Đã thanh toán</td>
                        <td>Hoàn thành</td>
                        <td>
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Thao tác</button>
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="@Url.Action("Detail", new { id = item.soPhieuDatHang })"><i class="fa fa-eye"></i> Xem</a></li>
                                    <li><a href="@Url.Action("XacNhanNhanHang", new { id = item.soPhieuDatHang })"><i class="fa fa-check"></i> Xác nhận</a></li>
                                    <li><a href="@Url.Action("Delete", new { id = item.soPhieuDatHang })"><i class="fa fa-trash"></i> Hủy</a></li>
                                </ul>
                            </div>
                        </td>
                    }

                    if (@item.daXacNhan == true && @item.daThanhToan == false)
                    {
                        <td>Đã xác nhận</td>
                        <td>Chưa thanh toán</td>
                        <td>Hoàn thành</td>
                        <td>
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Thao tác</button>
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="@Url.Action("Detail", new { id = item.soPhieuDatHang })"><i class="fa fa-eye"></i> Xem</a></li>
                                    <li><a href="@Url.Action("XacNhanThanhToan", new { id = item.soPhieuDatHang })"><i class="fa fa-credit-card"></i> Thanh toán</a></li>
                                    <li><a href="@Url.Action("Delete", new { id = item.soPhieuDatHang })"><i class="fa fa-trash"></i> Hủy</a></li>
                                </ul>
                            </div>
                        </td>
                    }

                    if (@item.daXacNhan == false && @item.daThanhToan == false)
                    {
                        <td>Chưa xác nhận</td>
                        <td>Chưa thanh toán</td>
                        <td>Hoàn thành</td>
                        <td>
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Thao tác</button>
                                <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="@Url.Action("Detail", new { id = item.soPhieuDatHang })"><i class="fa fa-eye"></i> Xem</a></li>
                                    <li><a href="@Url.Action("XacNhanNhanHang", new { id = item.soPhieuDatHang })"><i class="fa fa-check"></i> Xác nhận</a></li>
                                    @*<li><a href="@Url.Action("XacNhanThanhToan", new { id = item.soPhieuDatHang })"><i class="fa fa-credit-card"></i> Thanh toán</a></li>*@
                                    <li><a href="@Url.Action("Delete", new { id = item.soPhieuDatHang })"><i class="fa fa-trash"></i> Hủy</a></li>
                                </ul>
                            </div>
                        </td>
                    }
                }
                else
                {
                    if (@item.daXacNhan == true || @item.daThanhToan == true)
                    {
                        <td>Đã xác nhận</td>
                        <td>Đã thanh toán</td>
                    }
                    else
                    {
                        <td>Chưa xác nhận</td>
                        <td>Chưa thanh toán</td>
                    }
                    <td>Đã hủy</td>
                    <td>
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" tabindex="-1">Thao tác</button>
                            <button type="button" class="btn btn-lg btn btn-danger btn-xs btn-push pull-right" data-toggle="dropdown" tabindex="-1">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li><a href="@Url.Action("Detail", new { id = item.soPhieuDatHang })"><i class="fa fa-eye"></i> Xem</a></li>

                            </ul>
                        </div>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

<div class="pull-left" style="padding-top:20px">
    <h3 class="panel-title">Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</h3>
</div>
<div class="pull-right">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>

Source code/C-SMS/Areas/Admin/Views/DatHang/Delete.cshtml
@model IEnumerable<Common.ViewModels.PhieuDatHangViewModel>

@{
    ViewBag.Title = "Hủy phiếu đặt hàng";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}

<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Phiếu Đặt Hàng</h2>
        <div class="breadcrumb-wrapper hidden-xs">
            @using (Html.BeginForm("Deletes", "DatHang"))
            {
                <button class="btn btn-sm btn-danger btn-xs btn-push" id="submit">
                    <i class="fa fa-trash"></i> Hủy Phiếu Đặt Hàng
                </button>
                <input value="" type="hidden" id="id" name="id" class="form-control input-sm" />
            }
        </div>
    </div>
    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="alert alert-danger1 fade in">
                <span><i class="fa fa-bullhorn"></i> Bạn có chắc chắn muốn hủy?</span>
            </div>

            @{Html.RenderAction("ThongTinPhieuDatHang", "DatHang");}
        </div>

    </div>
</section>

<script src="~/Scripts/bootstrap.min.js"></script>
<script>
    $("#submit").on('click keyup input propertychange paste change', function () {
        var str1 = document.getElementById("soPhieuDatHang").value;
        $('#id').val(str1);
    });
</script>

Source code/C-SMS/Areas/Admin/Views/DatHang/Detail.cshtml
@{
    ViewBag.Title = "Thông tin chi tiết phiếu đặt hàng";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}


<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Phiếu Đặt Hàng</h2>
        <div class="breadcrumb-wrapper hidden-xs">
            <button class="btn btn-lg btn-success btn-xs btn-push" onclick="@("window.location.href='" + @Url.Action("Index", "DatHang") + "'"); ">
                <i class="glyphicon glyphicon-arrow-left"></i> Quay lại
            </button>
        </div>
    </div>
    <div class="body-content animated fadeIn">
        <div class="row">
            @{Html.RenderAction("ThongTinPhieuDatHang", "DatHang");}

        </div>
    </div>
</section>
<script src="~/Scripts/bootstrap.min.js"></script>

Source code/C-SMS/Areas/Admin/Views/DatHang/Index.cshtml
@model IEnumerable<Common.ViewModels.PhieuDatHangViewModel>
@using Common.ViewModels
@{
    ViewBag.Title = "Danh sách phiếu đặt hàng";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}

<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Phiếu Đặt Hàng</h2>
    </div>

    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="panel rounded shadow">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h3 class="panel-title">Danh sách phiếu đặt hàng</h3>
                        </div>
                        <div class="clearfix"></div>
                    </div><!-- /.panel-heading -->

                    <div class="panel-body">
                        <div class="form-body">
                            @using(Ajax.BeginForm("DanhSachPhieuDatHang", "DatHang", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "list", HttpMethod = "Get" }, new { id = "filter_div" }))
                            {
                                <div class="form-group">
                                    <div class="col-md-6">
                                        <label>Từ ngày</label>
                                        <input type="date" id="dateFrom" name="dateFrom" data-date-format="dd/mm/yyyy" required class="form-control rounded" />

                                    </div>
                                    <div class="col-md-6">
                                        <label>Đến ngày</label>
                                        <div class="input-group">
                                            <input type="date" id="dateTo" name="dateTo" required class="form-control rounded" />
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            }

                            @using(Ajax.BeginForm("DanhSachPhieuDatHang", "DatHang", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "list", HttpMethod = "Get" }, new { id = "filter_div" }))
                            {
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label>Trạng thái</label>
                                        <div class="input-group">
                                            @Html.DropDownList("trangthai", new SelectList(ViewBag.trangthai, "Value", "Text"), new { @class = "form-control rounded" })
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            }

                            @using (Ajax.BeginForm("DanhSachPhieuDatHang", "DatHang", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "list", HttpMethod = "Get" }, new { id = "filter_div" }))
                            {
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label>Tìm Kiếm</label>
                                        <div class="input-group">
                                            @Html.TextBox("SearchString", null, new { @class = "form-control rounded", @placeholder = "Tìm kiếm theo số phiếu, tên khách hàng, số điện thoại" })
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            }
                            <div id="list">
                                @{Html.RenderAction("DanhSachPhieuDatHang", "DatHang");}
                            </div>
                        </div><!-- /.form-body -->

                    </div><!-- /.panel-body -->
                </div><!-- /.panel -->
                <!--/ End input fields - basic form-->
            </div><!-- /.col-md-6 -->
        </div>
    </div>
</section>

<script src="~/Scripts/bootstrap.min.js"></script>

Source code/C-SMS/Areas/Admin/Views/DatHang/ThongTinPhieuDatHang.cshtml
@using Common.Ultil

<div class="col-md-8">
    <!-- Start bordered form -->
    <div class="panel rounded shadow">
        <div class="panel-heading">
            <div class="pull-left">
                <h3 class="panel-title">Thông tin sản phẩm</h3>
            </div>

            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        <div class="panel-body no-padding">
            <div class="form-body">
                <div class="table-responsive mb-20">
                    <table class="table table-bordered">
                        <tr>
                            <td>Sản Phẩm</td>
                            <td>Đơn giá</td>
                            <td>Số lượng</td>
                            <td>Thành tiền</td>
                        </tr>

                        @foreach (var item in ViewBag.chiTietPhieuDatHang)
                        {
                            FormatNumber number = new FormatNumber();
                            <tr>
                                <td>@item.tenHangHoa</td>
                                <td>@item.gia</td>
                                <td>@item.soLuong</td>
                                <td>@number.FormatNumbers(@item.thanhTien.ToString())</td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="panel rounded shadow">
        <div class="panel-heading">
            <div class="pull-left">
                <h3 class="panel-title">Thông tin phiếu bán hàng</h3>
            </div>
            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        <div class="panel-body no-padding">
            <form class="form-horizontal form-bordered" role="form">
                <div class="form-body">
                    @foreach (var a in ViewBag.phieuDatHang)
                    {
                        FormatNumber Number = new FormatNumber();
                        <div class="x_content">
                            <div class="form-group">
                                <label for="firstname-1" class="col-sm-4 control-label">Số phiếu</label>
                                <div class="col-sm-8">
                                    <input value="@a.soPhieuDatHang" id="soPhieuDatHang" type="text" class="form-control rounded" disabled="disabled" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password-1" class="col-sm-4 control-label">Ngày đặt</label>
                                <div class="col-sm-8">
                                    <input value="@a.ngayDat.ToString("dd/MM/yyyy")" disabled="disabled" type="text" class="form-control rounded" />

                                </div>
                            </div><!-- /.form-group -->
                           
                            <div class="form-group">
                                <label for="firstname-1" class="col-sm-4 control-label">Khách hàng</label>
                                <div class="col-sm-8">
                                    <input value="@a.tenKhachHang" type="text" class="form-control rounded" disabled="disabled" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="firstname-1" class="col-sm-4 control-label">Số điện thoại</label>
                                <div class="col-sm-8">
                                    <input value="@a.soDienThoai" type="text" class="form-control rounded" disabled="disabled" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="firstname-1" class="col-sm-4 control-label">Địa chỉ</label>
                                <div class="col-sm-8">
                                    <textarea placeholder="Ghi chú viết tại đây" class="form-control rounded" disabled="disabled">@a.diaChi</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="firstname-1" class="col-sm-4 control-label">Email</label>
                                <div class="col-sm-8">
                                    <input value="@a.email" type="text" class="form-control rounded" disabled="disabled" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="firstname-1" class="col-sm-4 control-label">Ghi chú</label>
                                <div class="col-sm-8">
                                    <textarea placeholder="Ghi chú viết tại đây" class="form-control rounded" disabled="disabled">@a.ghiChu</textarea>
                                </div>
                            </div>
                            <div class="form-group form-group-divider">
                                <div class="form-inner">
                                    <h4 class="no-margin">Thông tin thanh toán</h4>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="firstname-1" class="col-sm-4 control-label">Tổng tiền</label>
                                <div class="col-sm-8">
                                    <input id="tongTien" value="@Number.FormatNumbers(@a.tongTien.ToString())" disabled="disabled" type="text" class="form-control rounded" />

                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-sm-12 col-xs-12" style="margin-left:0%">
                            <label class="control-label col-md-12 col-sm-2 col-xs-12" style="color:red">(*) Lưu ý tiền được tính theo VNĐ</label>
                        </div>
                    }
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/Scripts/bootstrap.min.js"></script>

Source code/C-SMS/Areas/Admin/Views/DatHang/XacNhanNhanHang.cshtml
@model IEnumerable<Common.ViewModels.PhieuDatHangViewModel>

@{
    ViewBag.Title = "Xác nhận phiếu đặt hàng";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}

<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Phiếu Đặt Hàng</h2>
        <div class="breadcrumb-wrapper hidden-xs">
            @using (Html.BeginForm("XacNhanNhanHangs", "DatHang"))
            {
                <button class="btn btn-sm btn-success btn-xs btn-push" id="submit">
                    <i class="fa fa-check"></i> Xác nhận thông tin phiếu đặt hàng
                </button>
                <input value="" type="hidden" id="id" name="id" class="form-control input-sm" />
            }
        </div>
    </div>
    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="alert alert-danger1 fade in">
                <span><i class="fa fa-bullhorn"></i> Bạn muốn xác nhận thông tin khách hàng của phiếu đặt hàng này?</span>
            </div>

            @{Html.RenderAction("ThongTinPhieuDatHang", "DatHang");}
        </div>

    </div>
</section>

<script src="~/Scripts/bootstrap.min.js"></script>

<script>
    $("#submit").on('click keyup input propertychange paste change', function () {
        var str1 = document.getElementById("soPhieuDatHang").value;
        $('#id').val(str1);
    });
</script>

Source code/C-SMS/Areas/Admin/Views/DatHang/XacNhanThanhToan.cshtml
@model IEnumerable<Common.ViewModels.PhieuDatHangViewModel>

@{
    ViewBag.Title = "Xác nhận phiếu đặt hàng";
    Layout = "~/Areas/Admin/Views/Layout/HomeLayout.cshtml";
}

<section id="page-content">
    <div class="header-content">
        <h2><i class="fa fa-list-alt"></i>Phiếu Đặt Hàng</h2>
        <div class="breadcrumb-wrapper hidden-xs">
           @using (Html.BeginForm("XacNhanThanhToans", "DatHang"))
           {
                <button class="btn btn-sm btn-success btn-xs btn-push" id="submit">
                    <i class="fa fa-check"></i> Xác nhận thanh toán phiếu đặt hàng
                </button>
                <input value="" type="hidden" id="id" name="id" class="form-control input-sm" />
           }
        </div>
    </div>
    <div class="body-content animated fadeIn">
        <div class="row">
            <div class="alert alert-danger1 fade in">
                <span><i class="fa fa-bullhorn"></i> Bạn muốn xác nhận khách hàng đã thanh toán?</span>
            </div>

            @{Html.RenderAction("ThongTinPhieuDatHang", "DatHang");}
        </div>

    </div>
</section>

<script src="~/Scripts/bootstrap.min.js"></script>

<script>
    $("#submit").on('click keyup input propertychange paste change', function () {
        var str1 = document.getElementById("soPhieuDatDang").value;
        $('#id').val(str1);
    });
</script>